### ISSUE TITLE
Only usable with teams?

### ISSUE THREAD

**Issue by sanderdatema** [f00b4r/strapi-plugin-vercel#2]
Since a teams ID is needed, I think it's not possible to use this plugin when on a free plan?

**Comment by f3l1x** [comment]
Hi, I didn't test it on personal account. But I think it should work well. Try to use your personal ID instead of team ID. Let me know.

**Comment by ndom91** [comment]
@here seems doable without a team. I just got it working with my personal account. 

The current paths were no longer valid though. I just put up a PR to fix them. After that is merged, it should work with personal accounts no problem. In fact, I think the `teamId` isn't even necessary.

**Comment by f3l1x** [comment]
Hi @sanderdatema  and @ndom91. Version 0.0.7 solved personal vs team deployments and also scoped tokens.
